### ISSUE TITLE
Add yourself to Contributors.md

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/ak-logger#12]
If you are starting with opensource contributions, this is best to start with.
just go ahead and add your details to Contributors.md file in the same format as other's details.

@vvscode @markost2549 
Since you guys have already contributed for us, why don't your name to Contributors.md and create a PR

**Comment by vvscode** [comment]
Cheers )) https://github.com/arshadkazmi42/ak-logger/pull/13
